openapi: 3.0.3
info:
  title: Movie API
  version: 1.0.0
  description: Hello its my moviesite . My name is Ernazar Jumagulov i am Python developmer!
paths:
  /api/{id}/:
    get:
      operationId: api_retrieve
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        required: true
      tags:
      - api
      security:
      - cookieAuth: []
      - basicAuth: []
      - tokenAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Movie'
          description: ''
    put:
      operationId: api_update
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        required: true
      tags:
      - api
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Movie'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Movie'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Movie'
        required: true
      security:
      - cookieAuth: []
      - basicAuth: []
      - tokenAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Movie'
          description: ''
    patch:
      operationId: api_partial_update
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        required: true
      tags:
      - api
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PatchedMovie'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/PatchedMovie'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/PatchedMovie'
      security:
      - cookieAuth: []
      - basicAuth: []
      - tokenAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Movie'
          description: ''
    delete:
      operationId: api_destroy
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        required: true
      tags:
      - api
      security:
      - cookieAuth: []
      - basicAuth: []
      - tokenAuth: []
      responses:
        '204':
          description: No response body
  /api/movie//:
    get:
      operationId: api_movie_retrieve
      tags:
      - api
      security:
      - cookieAuth: []
      - basicAuth: []
      - tokenAuth: []
      responses:
        '200':
          description: No response body
    post:
      operationId: api_movie_create
      tags:
      - api
      security:
      - cookieAuth: []
      - basicAuth: []
      - tokenAuth: []
      responses:
        '201':
          description: No response body
  /api/movie//{id}/:
    get:
      operationId: api_movie_retrieve_2
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        description: A unique integer value identifying this Фильмы.
        required: true
      tags:
      - api
      security:
      - cookieAuth: []
      - basicAuth: []
      - tokenAuth: []
      responses:
        '200':
          description: No response body
    put:
      operationId: api_movie_update
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        description: A unique integer value identifying this Фильмы.
        required: true
      tags:
      - api
      security:
      - cookieAuth: []
      - basicAuth: []
      - tokenAuth: []
      responses:
        '200':
          description: No response body
    patch:
      operationId: api_movie_partial_update
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        description: A unique integer value identifying this Фильмы.
        required: true
      tags:
      - api
      security:
      - cookieAuth: []
      - basicAuth: []
      - tokenAuth: []
      responses:
        '200':
          description: No response body
    delete:
      operationId: api_movie_destroy
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        description: A unique integer value identifying this Фильмы.
        required: true
      tags:
      - api
      security:
      - cookieAuth: []
      - basicAuth: []
      - tokenAuth: []
      responses:
        '204':
          description: No response body
  /api/profiles/:
    get:
      operationId: api_profiles_list
      tags:
      - api
      security:
      - cookieAuth: []
      - basicAuth: []
      - tokenAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Movie'
          description: ''
    post:
      operationId: api_profiles_create
      tags:
      - api
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Movie'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Movie'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Movie'
        required: true
      security:
      - cookieAuth: []
      - basicAuth: []
      - tokenAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Movie'
          description: ''
components:
  schemas:
    Movie:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        title:
          type: string
          maxLength: 200
        description:
          type: string
        release_date:
          type: string
          format: date
          readOnly: true
        country:
          type: string
          maxLength: 200
        duration:
          type: integer
          maximum: 2147483647
          minimum: 0
          description: Продолжительность в минутах
        poster:
          type: string
          format: uri
        video1:
          type: string
          format: uri
          nullable: true
        video2:
          type: string
          format: uri
          nullable: true
        video3:
          type: string
          format: uri
          nullable: true
        director:
          type: integer
          nullable: true
        screenwriter:
          type: integer
          nullable: true
        producer:
          type: integer
          nullable: true
        genres:
          type: array
          items:
            type: integer
        categories:
          type: array
          items:
            type: integer
        cast:
          type: array
          items:
            type: integer
      required:
      - cast
      - categories
      - country
      - description
      - duration
      - genres
      - id
      - poster
      - release_date
      - title
    PatchedMovie:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        title:
          type: string
          maxLength: 200
        description:
          type: string
        release_date:
          type: string
          format: date
          readOnly: true
        country:
          type: string
          maxLength: 200
        duration:
          type: integer
          maximum: 2147483647
          minimum: 0
          description: Продолжительность в минутах
        poster:
          type: string
          format: uri
        video1:
          type: string
          format: uri
          nullable: true
        video2:
          type: string
          format: uri
          nullable: true
        video3:
          type: string
          format: uri
          nullable: true
        director:
          type: integer
          nullable: true
        screenwriter:
          type: integer
          nullable: true
        producer:
          type: integer
          nullable: true
        genres:
          type: array
          items:
            type: integer
        categories:
          type: array
          items:
            type: integer
        cast:
          type: array
          items:
            type: integer
  securitySchemes:
    basicAuth:
      type: http
      scheme: basic
    cookieAuth:
      type: apiKey
      in: cookie
      name: sessionid
    tokenAuth:
      type: apiKey
      in: header
      name: Authorization
      description: Token-based authentication with required prefix "Token"
