# Generated by Django 4.2 on 2024-07-20 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0002_movie_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='country',
            field=models.CharField(default=2, max_length=200),
            preserve_default=False,
        ),
    ]
