# Generated by Django 4.2 on 2024-07-20 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0004_producer_screenwriter_alter_movie_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='actorphoto1',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='actorphoto2',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='actorphoto3',
        ),
    ]
