# Generated by Django 4.2 on 2024-07-20 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0008_movie_bigimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='bigimage',
        ),
        migrations.AddField(
            model_name='movie',
            name='banner_image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
