# Generated by Django 4.2 on 2024-07-20 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0009_remove_movie_bigimage_movie_banner_image_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='banner_image_url',
        ),
    ]
