# Generated by Django 4.2 on 2024-07-21 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0011_series_season_episode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episode',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='episodes/'),
        ),
    ]
