# Generated by Django 4.2 on 2024-07-22 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0013_comment_series'),
    ]

    operations = [
        migrations.RenameField(
            model_name='episode',
            old_name='video',
            new_name='video1',
        ),
        migrations.AddField(
            model_name='episode',
            name='video2',
            field=models.FileField(blank=True, null=True, upload_to='episodes/'),
        ),
        migrations.AddField(
            model_name='episode',
            name='video3',
            field=models.FileField(blank=True, null=True, upload_to='episodes/'),
        ),
    ]
