# Generated by Django 4.2 on 2024-07-22 06:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('movie', '0014_rename_video_episode_video1_episode_video2_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userfavoritemovies',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='userfavoritemovies',
            name='series',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='movie.series'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='userfavoritemovies',
            unique_together={('user', 'movie', 'series')},
        ),
    ]
